apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-mapped-pv
spec:
  storageClassName: nfssharesc
  capacity: 
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/nfsvolume/10megpv