apiVersion: v1
kind: Service
metadata:
  namespace: pv-demo
  name: host-mapped-service
spec:
  selector: 
    app: host-mapped-site
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033