apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers: 
        - image: mysql:5.6
          securityContext:
            runAsUser: 4000
            allowPrivilegeEscalation: false
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts: 
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim: 
            claimName: mysql-pv-claim
