apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: elk
spec: 
  selector: 
    matchLabels: 
      app: elastic
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: elastic
    spec: 
      containers: 
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
          name: elasticsearch
          env:
            - name: node.name
              value: es01
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
          volumeMounts: 
            - name: elastic-persistent-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elastic-persistent-storage
          persistentVolumeClaim: 
            claimName: elastic-pvc
