kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: elastic-pvc
  namespace: elk
spec:
  storageClassName: nfs-client
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "500Mi"