apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: elk
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
      nodePort: 30921
  selector:
    app: kibana