apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
spec:
  type: NodePort
  ports:
    - port: 2368
      targetPort: 2368
      protocol: TCP
      name: http
      nodePort: 30955
  selector:
    app: ghost